import { User, Post } from './types';

export const seedUsers: User[] = [
  {
    id: 'user_1',
    name: 'Neo',
    email: 'neo@hackmate.io',
    github: 'neo',
    password_plaintext: 'password',
    privacy: 'public',
    hackathonsAttended: ['post_1', 'post_2', 'post_5'],
    collaborations: 2,
    wins: 1,
  },
  {
    id: 'user_2',
    name: 'Trinity',
    email: 'trinity@hackmate.io',
    github: 'trinity',
    password_plaintext: 'password',
    privacy: 'public',
    hackathonsAttended: ['post_1', 'post_5'],
    collaborations: 1,
    wins: 1,
  },
];

export const seedPosts: Post[] = [
  {
    id: 'post_1',
    authorId: 'user_1',
    authorName: 'Neo',
    type: 'FAME',
    venue: 'Mega-City Hack 2024',
    date: '2024-07-20',
    achievement: '1st Place',
    teamMembers: ['Neo', 'Trinity'],
    description: 'Cracked the mainframe and built a decentralized future. Our project, "Elysium", took home the grand prize!',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
    views: 1337,
    reactions: { chat: 10, congrats: 150, bestOfLuck: 5 },
  },
  {
    id: 'post_2',
    authorId: 'user_2',
    authorName: 'Trinity',
    type: 'TEAMMATE',
    venue: 'Cyberia Hackathon',
    date: '2024-08-15',
    currentTeam: 3,
    requiredTeam: 5,
    description: 'Looking for two more backend wizards to join our squad for the upcoming Cyberia hackathon. We are focusing on AI-driven security solutions. If you know Python and ML, hit us up!',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
    views: 450,
    reactions: { chat: 25, congrats: 30, bestOfLuck: 80 },
  },
  {
    id: 'post_3',
    authorId: 'user_1',
    authorName: 'Neo',
    type: 'HACKATHON',
    venue: 'Zion Mainframe',
    date: '2024-09-01',
    description: 'The annual Zion defense hackathon is back! This year\'s theme is "Building a Better Tomorrow". 48 hours of intense coding, great food, and amazing prizes. Register now!',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    views: 980,
    reactions: { chat: 5, congrats: 20, bestOfLuck: 200 },
  },
  {
    id: 'post_4',
    authorId: 'user_2',
    authorName: 'Trinity',
    type: 'COLLABORATION',
    idea: 'Real-time P2P Encrypted Messenger',
    skills: ['React Native', 'WebSockets', 'Cryptography'],
    teamCount: 1,
    description: 'I have a project idea for a fully E2E encrypted messenger. Looking for collaborators who are passionate about privacy and have experience with mobile dev and networking. This is a long-term project, not for a hackathon.',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
    views: 732,
    reactions: { chat: 40, congrats: 90, bestOfLuck: 15 },
  },
  {
    id: 'post_5',
    authorId: 'user_1',
    authorName: 'Neo',
    type: 'FAME',
    venue: 'Code Matrix 2023',
    date: '2023-12-10',
    achievement: 'Most Innovative Hack',
    teamMembers: ['Neo', 'Trinity', 'Morpheus'],
    description: 'We didn\'t win first place, but our reality-bending AR project got the "Most Innovative" award. A great learning experience!',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 180).toISOString(),
    views: 2048,
    reactions: { chat: 18, congrats: 300, bestOfLuck: 10 },
  },
  {
    id: 'post_6',
    authorId: 'user_2',
    authorName: 'Trinity',
    type: 'TEAMMATE',
    venue: 'DevGrid Finals',
    date: '2024-10-05',
    currentTeam: 1,
    requiredTeam: 4,
    description: 'Frontend dev here, looking to form a team for the DevGrid Finals. My strengths are in UI/UX and React. Need a backend guru, a data scientist, and a DevOps specialist. Let\'s build something amazing.',
    createdAt: new Date().toISOString(),
    views: 15,
    reactions: { chat: 2, congrats: 1, bestOfLuck: 10 },
  },
];
