import { User, Post } from './types';

export const seedUsers: User[] = [
  {
    id: 'user_1',
    name: 'Neo',
    email: 'neo@hackmate.io',
    github: 'neo',
    password_plaintext: 'password',
    avatarUrl: 'https://picsum.photos/seed/user1/150/150',
    privacy: 'public',
    hackathonsAttended: ['post_1', 'post_2', 'post_5'],
    collaborations: 2,
    wins: 1,
  },
  {
    id: 'user_2',
    name: 'Trinity',
    email: 'trinity@hackmate.io',
    github: 'trinity',
    password_plaintext: 'password',
    avatarUrl: 'https://picsum.photos/seed/user2/150/150',
    privacy: 'public',
    hackathonsAttended: ['post_1', 'post_5'],
    collaborations: 1,
    wins: 1,
  },
];

export const seedPosts: Post[] = [
  {
    id: 'post_1',
    authorId: 'user_1',
    authorName: 'Neo',
    authorAvatarUrl: 'https://picsum.photos/seed/user1/150/150',
    type: 'FAME',
    venue: 'Mega-City Hack 2024',
    date: '2024-07-20',
    achievement: '1st Place',
    teamMembers: ['Neo', 'Trinity'],
    description: 'Cracked the mainframe and built a decentralized future. Our project, "Elysium", took home the grand prize!',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
    views: 1337,
    reactions: { chat: 10, congrats: 150, bestOfLuck: 5 },
  },
  {
    id: 'post_2',
    authorId: 'user_2',
    authorName: 'Trinity',
    authorAvatarUrl: 'https://picsum.photos/seed/user2/150/150',
    type: 'TEAMMATE',
    venue: 'Cyberia Hackathon',
    date: '2024-08-15',
    currentTeam: 3,
    requiredTeam: 5,
    description: 'Looking for two more backend wizards to join our squad for the upcoming Cyberia hackathon. We are focusing on AI-driven security solutions. If you know Python and ML, hit us up!',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
    views: 450,
    reactions: { chat: 25, congrats: 30, bestOfLuck: 80 },
  },
  {
    id: 'post_3',
    authorId: 'user_1',
    authorName: 'Neo',
    authorAvatarUrl: 'https://picsum.photos/seed/user1/150/150',
    type: 'HACKATHON',
    venue: 'Zion Mainframe',
    date: '2024-09-01',
    description: 'The annual Zion defense hackathon is back! This year\'s theme is "Building a Better Tomorrow". 48 hours of intense coding, great food, and amazing prizes. Register now!',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    views: 980,
    reactions: { chat: 5, congrats: 20, bestOfLuck: 200 },
  },
  {
    id: 'post_4',
    authorId: 'user_2',
    authorName: 'Trinity',
    authorAvatarUrl: 'https://picsum.photos/seed/user2/150/150',
    type: 'COLLABORATION',
    idea: 'Real-time P2P Encrypted Messenger',
    skills: ['React Native', 'WebSockets', 'Cryptography'],
    teamCount: 1,
    description: 'I have a project idea for a fully E2E encrypted messenger. Looking for collaborators who are passionate about privacy and have experience with mobile dev and networking. This is a long-term project, not for a hackathon.',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
    views: 732,
    reactions: { chat: 40, congrats: 90, bestOfLuck: 15 },
  },
  {
    id: 'post_5',
    authorId: 'user_1',
    authorName: 'Neo',
    authorAvatarUrl: 'https://picsum.photos/seed/user1/150/150',
    type: 'FAME',
    venue: 'Code Matrix 2023',
    date: '2023-12-10',
    achievement: 'Most Innovative Hack',
    teamMembers: ['Neo', 'Trinity', 'Morpheus'],
    description: 'We didn\'t win first place, but our reality-bending AR project got the "Most Innovative" award. A great learning experience!',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 180).toISOString(),
    views: 2048,
    reactions: { chat: 18, congrats: 300, bestOfLuck: 10 },
  },
  {
    id: 'post_6',
    authorId: 'user_2',
    authorName: 'Trinity',
    authorAvatarUrl: 'https://picsum.photos/seed/user2/150/150',
    type: 'TEAMMATE',
    venue: 'DevGrid Finals',
    date: '2024-10-05',
    currentTeam: 1,
    requiredTeam: 4,
    description: 'Frontend dev here, looking to form a team for the DevGrid Finals. My strengths are in UI/UX and React. Need a backend guru, a data scientist, and a DevOps specialist. Let\'s build something amazing.',
    createdAt: new Date().toISOString(),
    views: 15,
    reactions: { chat: 2, congrats: 1, bestOfLuck: 10 },
  },
  {
    id: 'post_7',
    authorId: 'user_1',
    authorName: 'Neo',
    authorAvatarUrl: 'https://picsum.photos/seed/user1/150/150',
    type: 'COLLABORATION',
    idea: 'AI agent for automated code refactoring',
    skills: ['TypeScript', 'ASTs', 'LLMs'],
    teamCount: 1,
    description: 'Looking for a partner to build an intelligent agent that can analyze codebases and suggest refactoring improvements. This is a research-oriented project with the potential to become a real product.',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(),
    views: 650,
    reactions: { chat: 30, congrats: 70, bestOfLuck: 20 },
  },
  {
    id: 'post_8',
    authorId: 'user_2',
    authorName: 'Trinity',
    authorAvatarUrl: 'https://picsum.photos/seed/user2/150/150',
    type: 'HACKATHON',
    venue: 'Quantum Leap Hack',
    date: '2024-11-11',
    description: 'Join the Quantum Leap Hackathon and work on cutting-edge quantum computing challenges. No prior quantum experience needed, just a creative mind and strong problem-solving skills.',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 10).toISOString(),
    views: 820,
    reactions: { chat: 12, congrats: 40, bestOfLuck: 150 },
  },
  {
    id: 'post_9',
    authorId: 'user_1',
    authorName: 'Neo',
    authorAvatarUrl: 'https://picsum.photos/seed/user1/150/150',
    type: 'TEAMMATE',
    venue: 'AI Safety Summit',
    date: '2024-09-25',
    currentTeam: 2,
    requiredTeam: 4,
    description: 'Our team is working on a project for the AI Safety Summit hackathon. We need a UI/UX designer and a frontend developer to help us create a compelling presentation. Our focus is on model alignment and interpretability.',
    createdAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    views: 99,
    reactions: { chat: 8, congrats: 5, bestOfLuck: 30 },
  },
  {
    id: 'post_10',
    authorId: 'user_2',
    authorName: 'Trinity',
    authorAvatarUrl: 'https://picsum.photos/seed/user2/150/150',
    type: 'FAME',
    venue: 'Hack The Planet 2023',
    date: '2023-10-22',
    achievement: 'Runner Up',
    teamMembers: ['Trinity', 'Ghost', 'Seraph'],
    description: 'We built a decentralized social network and got second place! It was a wild 48 hours. Huge thanks to my amazing team.',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 300).toISOString(),
    views: 1800,
    reactions: { chat: 50, congrats: 400, bestOfLuck: 25 },
  },
  {
    id: 'post_11',
    authorId: 'user_1',
    authorName: 'Neo',
    authorAvatarUrl: 'https://picsum.photos/seed/user1/150/150',
    type: 'HACKATHON',
    venue: 'Decentralized Future Conf',
    date: '2025-01-20',
    description: 'A hackathon focused on building the next generation of decentralized applications. Topics include DeFi, DAOs, and decentralized identity. Come and build with us!',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(),
    views: 400,
    reactions: { chat: 3, congrats: 10, bestOfLuck: 100 },
  },
  {
    id: 'post_12',
    authorId: 'user_2',
    authorName: 'Trinity',
    authorAvatarUrl: 'https://picsum.photos/seed/user2/150/150',
    type: 'COLLABORATION',
    idea: 'Open Source Hardware Security Module (HSM)',
    skills: ['Embedded Systems', 'C++', 'Security'],
    teamCount: 2,
    description: 'Looking for experts in embedded systems and cryptography to collaborate on an open-source HSM. The goal is to create a low-cost, verifiable, and secure hardware solution for key management.',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 20).toISOString(),
    views: 555,
    reactions: { chat: 22, congrats: 65, bestOfLuck: 42 },
  },
];
